/**
 * Sherpa Component Catalog
 *
 * Machine-readable inventory of all components exported from @sherpa/studio-ui.
 * Each entry documents the component's visual pattern, domain, tokens, and
 * composition relationships.
 *
 * Sync test: src/__tests__/catalog-sync.test.ts
 */

export interface ComponentCatalogEntry {
  /** PascalCase export name */
  name: string
  /** One-line description */
  description: string
  /** Which design pattern it implements (null if composite/unique) */
  pattern:
    | "glass-panel"
    | "status-indicator"
    | "data-readout"
    | "timeline"
    | "pipeline-bar"
    | "card-list"
    | "section-header"
    | "badge"
    | null
  /** Key variant prop values */
  variants?: string[]
  /** CSS custom property names referenced (without --) */
  tokens: string[]
  /** Other studio-ui components commonly composed with */
  composedWith?: string[]
  /** Whether this is a client component ("use client") */
  isClient: boolean
  /** Functional domain */
  domain:
    | "governance"
    | "data-viz"
    | "hub"
    | "content"
    | "layout"
    | "agents"
    | "domain-panels"
  /** Source module path (matches barrel export, without ./ prefix) */
  source: string
}

// ── Catalog entries ────────────────────────────────────────────────

export const COMPONENT_CATALOG: ComponentCatalogEntry[] = [
  // ── Hub ────────────────────────────────────────────────────────
  {
    name: "HubPanel",
    description:
      "Base glass panel with variant-driven accent bar and glow effects",
    pattern: "glass-panel",
    variants: [
      "process",
      "portfolio",
      "activity",
      "docs",
      "conventions",
      "skills",
      "primitives",
      "api",
      "workforce",
      "sessions",
      "transit-content",
      "tasks",
      "mcp",
      "workflow",
    ],
    tokens: [
      "glass-bg",
      "glass-border",
      "glass-shadow",
      "glass-bg-hover",
      "glass-border-hover",
      "glass-shadow-hover",
      "color-copper",
      "color-gold",
      "color-bronze",
      "color-eclipse",
      "color-primitive",
      "color-api",
      "color-session",
      "color-transit",
      "color-mcp",
    ],
    isClient: false,
    domain: "hub",
    source: "hub-panel",
  },
  {
    name: "HubCard",
    description: "Gold-accented stat card with label/value pairs",
    pattern: null,
    tokens: ["border-gold", "color-gold"],
    isClient: false,
    domain: "hub",
    source: "hub-card",
  },
  {
    name: "HubActivityPanel",
    description: "Recent activity timeline with gold spine and date dots",
    pattern: "timeline",
    tokens: ["glass-border", "color-gold"],
    composedWith: ["HubPanel", "ActivityDescription"],
    isClient: false,
    domain: "hub",
    source: "hub-activity-panel",
  },
  {
    name: "HubApiPanel",
    description: "API endpoint catalog with method badges and levels",
    pattern: null,
    tokens: [],
    composedWith: ["HubPanel", "LevelBadge", "ApiMethodBadge"],
    isClient: false,
    domain: "hub",
    source: "hub-api-panel",
  },
  {
    name: "HubConventionsPanel",
    description: "Governance conventions with glass badges and status LEDs",
    pattern: "status-indicator",
    tokens: ["glass-border", "glass-bg"],
    composedWith: ["HubPanel"],
    isClient: false,
    domain: "hub",
    source: "hub-conventions-panel",
  },
  {
    name: "HubDocsPanel",
    description: "Documentation browser with age-based freshness colors",
    pattern: null,
    tokens: ["color-bronze"],
    composedWith: ["HubPanel", "DocsCategoryChart"],
    isClient: false,
    domain: "hub",
    source: "hub-docs-panel",
  },
  {
    name: "HubMcpPanel",
    description: "MCP server status with LED indicators and tool inventory",
    pattern: "status-indicator",
    tokens: ["color-mcp"],
    composedWith: ["HubPanel"],
    isClient: false,
    domain: "hub",
    source: "hub-mcp-panel",
  },
  {
    name: "HubOperationalPulse",
    description: "Dot-separated operational metrics readout",
    pattern: "data-readout",
    tokens: [],
    isClient: false,
    domain: "hub",
    source: "hub-operational-pulse",
  },
  {
    name: "HubPortfolioPanel",
    description: "Portfolio health with app type pills and chart",
    pattern: null,
    tokens: ["color-gold"],
    composedWith: ["HubPanel", "PortfolioHealthChart"],
    isClient: false,
    domain: "hub",
    source: "hub-portfolio-panel",
  },
  {
    name: "HubPrimitivesPanel",
    description: "Primitive catalog display with level badges",
    pattern: null,
    tokens: [],
    composedWith: ["HubPanel", "LevelBadge"],
    isClient: false,
    domain: "hub",
    source: "hub-primitives-panel",
  },
  {
    name: "HubProcessPanel",
    description: "Initiative pipeline with momentum badges and status LEDs",
    pattern: "status-indicator",
    tokens: ["color-copper", "color-gold"],
    composedWith: ["HubPanel", "ProcessPipelineChart", "StatusBadge"],
    isClient: false,
    domain: "hub",
    source: "hub-process-panel",
  },
  {
    name: "HubSessionsPanel",
    description: "Session metrics and recent session list",
    pattern: null,
    tokens: [],
    composedWith: ["HubPanel"],
    isClient: false,
    domain: "hub",
    source: "hub-sessions-panel",
  },
  {
    name: "HubSkillsPanel",
    description: "Available skills list with eclipse accent hover",
    pattern: null,
    tokens: ["color-eclipse"],
    composedWith: ["HubPanel"],
    isClient: false,
    domain: "hub",
    source: "hub-skills-panel",
  },
  {
    name: "HubStagger",
    description:
      "Framer Motion staggered entrance animation for hub panels",
    pattern: null,
    variants: ["fade", "panel"],
    tokens: ["color-ambient-warm"],
    isClient: true,
    domain: "hub",
    source: "hub-stagger",
  },
  {
    name: "HubTasksPanel",
    description: "Task board with 5-state status dots and glass badges",
    pattern: "status-indicator",
    tokens: ["color-copper", "glass-border", "glass-bg"],
    composedWith: ["HubPanel"],
    isClient: false,
    domain: "hub",
    source: "hub-tasks-panel",
  },
  {
    name: "HubWorkflowPanel",
    description: "Workflow stage pills with glass styling and arrows",
    pattern: null,
    tokens: ["glass-border", "glass-bg"],
    composedWith: ["HubPanel"],
    isClient: false,
    domain: "hub",
    source: "hub-workflow-panel",
  },
  {
    name: "HubWorkforcePanel",
    description: "Agent role list grouped by category with eclipse hover",
    pattern: null,
    tokens: ["color-eclipse"],
    composedWith: ["HubPanel"],
    isClient: false,
    domain: "hub",
    source: "hub-workforce-panel",
  },

  // ── Governance ─────────────────────────────────────────────────
  {
    name: "ArchiveButton",
    description: "Alert dialog trigger for archiving initiatives",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "governance",
    source: "archive-restore-buttons",
  },
  {
    name: "InitiativeActionBar",
    description: "Prompt copy buttons for initiative lifecycle actions",
    pattern: null,
    tokens: [],
    composedWith: ["PromptCopyButton"],
    isClient: true,
    domain: "governance",
    source: "initiative-action-bar",
  },
  {
    name: "InitiativeCard",
    description: "Grid card with title, summary, type/risk badges",
    pattern: "card-list",
    tokens: ["border-gold", "color-gold"],
    composedWith: ["StatusBadge"],
    isClient: false,
    domain: "governance",
    source: "initiative-card",
  },
  {
    name: "InitiativeContents",
    description: "Collapsible directory tree of initiative files",
    pattern: null,
    tokens: ["color-copper"],
    isClient: true,
    domain: "governance",
    source: "initiative-contents",
  },
  {
    name: "InitiativeFileTree",
    description: "Animated file tree with annotation-based icons and prompts",
    pattern: null,
    tokens: ["color-gold", "color-copper", "color-bronze"],
    composedWith: ["PromptCopyButton", "StatusBadge"],
    isClient: true,
    domain: "governance",
    source: "initiative-file-tree",
  },
  {
    name: "InitiativeLifecycleBar",
    description: "5-stage lifecycle progress bar with next-action prompts",
    pattern: "pipeline-bar",
    tokens: ["border-gold", "color-gold", "color-copper"],
    composedWith: ["PromptCopyButton"],
    isClient: true,
    domain: "governance",
    source: "initiative-lifecycle-bar",
  },
  {
    name: "InitiativeLifecycleHero",
    description: "Animated segmented progress track with glass styling",
    pattern: "glass-panel",
    tokens: ["glass-border", "glass-bg", "color-gold", "color-copper"],
    composedWith: ["PromptCopyButton"],
    isClient: true,
    domain: "governance",
    source: "initiative-lifecycle-hero",
  },
  {
    name: "InitiativePlaybookSection",
    description: "Playbook plays list with prompt copy buttons and status tracking",
    pattern: null,
    tokens: [],
    composedWith: ["PromptCopyButton"],
    isClient: true,
    domain: "governance",
    source: "initiative-playbook-section",
  },
  {
    name: "InitiativeMetadataGrid",
    description: "Metadata grid with type pill, risk indicator, animated stats",
    pattern: null,
    tokens: [
      "color-gold",
      "color-copper",
      "glass-border",
      "glass-bg",
    ],
    isClient: true,
    domain: "governance",
    source: "initiative-metadata-grid",
  },
  {
    name: "InitiativeOverviewSection",
    description: "Composite overview with hero, metadata, file tree, sessions",
    pattern: null,
    tokens: ["border-gold", "color-dark-bronze", "color-eclipse"],
    composedWith: [
      "InitiativeLifecycleHero",
      "ProposalActions",
      "InitiativeMetadataGrid",
      "InitiativeFileTree",
      "InitiativeSessionsSection",
      "ChartRenderer",
    ],
    isClient: true,
    domain: "governance",
    source: "initiative-overview-section",
  },
  {
    name: "InitiativeSessionsSection",
    description: "Session list with model badges, token bars, and outcomes",
    pattern: null,
    tokens: [
      "color-gold",
      "color-copper",
      "color-bronze",
      "color-session",
    ],
    isClient: true,
    domain: "governance",
    source: "initiative-sessions-section",
  },
  {
    name: "LifecyclePipeline",
    description: "Horizontal pipeline of initiative statuses with count pills",
    pattern: "pipeline-bar",
    tokens: [],
    isClient: false,
    domain: "governance",
    source: "lifecycle-pipeline",
  },
  {
    name: "ProcessActionBar",
    description: "Dynamic action buttons based on process node kind",
    pattern: null,
    tokens: ["color-gold", "color-copper"],
    composedWith: ["PromptCopyButton"],
    isClient: true,
    domain: "governance",
    source: "process-action-bar",
  },
  {
    name: "ProcessActivityTab",
    description: "Vertical activity timeline with classified entry types",
    pattern: "timeline",
    tokens: ["color-gold", "color-copper", "color-bronze"],
    isClient: true,
    domain: "governance",
    source: "process-activity-tab",
  },
  {
    name: "ProcessDashboard",
    description: "Stats grid with gold-bordered cards and pipeline charts",
    pattern: null,
    tokens: ["border-gold", "color-gold"],
    composedWith: ["LifecyclePipeline", "ProcessPipelineChart"],
    isClient: false,
    domain: "governance",
    source: "process-dashboard",
  },
  {
    name: "ProcessDetailPane",
    description: "Multi-tab detail view with overview, research, activity, graph",
    pattern: null,
    tokens: ["color-gold", "color-warm-charcoal", "border-gold"],
    composedWith: [
      "ProcessKindIcon",
      "StatusBadge",
      "ProcessActionBar",
      "ProcessActivityTab",
      "InitiativeOverviewSection",
      "ProcessGraph",
      "ProcessResearchTab",
    ],
    isClient: true,
    domain: "governance",
    source: "process-detail-pane",
  },
  {
    name: "ProcessFilterBar",
    description: "Kind pills, status dropdown, sort buttons, and search input",
    pattern: null,
    tokens: ["color-gold"],
    isClient: true,
    domain: "governance",
    source: "process-filter-bar",
  },
  {
    name: "ProcessItemList",
    description: "Scrollable tree-view list with selection and staleness colors",
    pattern: "card-list",
    tokens: ["color-gold", "color-dark-bronze", "color-warm-charcoal"],
    composedWith: ["ProcessKindIcon", "StatusBadge"],
    isClient: true,
    domain: "governance",
    source: "process-item-list",
  },
  {
    name: "ProcessKindIcon",
    description: "Lucide icon lookup by process view kind",
    pattern: null,
    tokens: [],
    isClient: false,
    domain: "governance",
    source: "process-kind-icon",
  },
  {
    name: "ProcessKindRail",
    description: "Vertical kind filter rail with gold active state",
    pattern: null,
    tokens: ["color-dark-bronze", "color-warm-charcoal", "color-gold"],
    composedWith: ["ProcessKindIcon"],
    isClient: true,
    domain: "governance",
    source: "process-kind-rail",
  },
  {
    name: "ProcessResearchTab",
    description: "Collapsible research iterations with file links",
    pattern: null,
    tokens: ["color-copper", "color-gold"],
    isClient: true,
    domain: "governance",
    source: "process-research-tab",
  },
  {
    name: "ProcessWorkspace",
    description: "3-column layout with kind rail, item list, and detail pane",
    pattern: null,
    tokens: [
      "color-dark-bronze",
      "color-warm-charcoal",
      "color-gold",
    ],
    composedWith: [
      "ProcessKindRail",
      "ProcessItemList",
      "ProcessDetailPane",
      "ResizeHandle",
    ],
    isClient: true,
    domain: "governance",
    source: "process-workspace",
  },
  {
    name: "ProposalActions",
    description: "Approve/decline alert dialogs with risk warnings",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "governance",
    source: "proposal-actions",
  },
  {
    name: "UnifiedCardClient",
    description: "Collapsible initiative card with tabbed detail content",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "governance",
    source: "unified-card-client",
  },
  {
    name: "UnifiedInitiativeCard",
    description: "Server component rendering initiative with merged workstream data",
    pattern: null,
    tokens: [],
    composedWith: ["UnifiedCardClient"],
    isClient: false,
    domain: "governance",
    source: "unified-initiative-card",
  },

  // ── Layout ─────────────────────────────────────────────────────
  {
    name: "ApiMethodBadge",
    description: "GET/POST method badge with semantic green/amber coloring",
    pattern: "badge",
    variants: ["GET", "POST"],
    tokens: [],
    isClient: false,
    domain: "layout",
    source: "api-method-badge",
  },
  {
    name: "AppTile",
    description: "App card with name, type, phase, health, and active indicator",
    pattern: "card-list",
    tokens: [],
    isClient: false,
    domain: "layout",
    source: "app-tile",
  },
  {
    name: "KindBadge",
    description: "TypeScript export kind badge with monospace semantic colors",
    pattern: "badge",
    variants: ["function", "interface", "type-alias", "variable", "enum"],
    tokens: [],
    isClient: false,
    domain: "layout",
    source: "kind-badge",
  },
  {
    name: "LevelBadge",
    description: "Abstraction level badge (L1-L5) with progressive intensity",
    pattern: "badge",
    variants: ["primitive", "gold"],
    tokens: [],
    isClient: false,
    domain: "layout",
    source: "level-badge",
  },
  {
    name: "LevelPeerStrip",
    description: "Compact peer card strip showing primitives at same level",
    pattern: null,
    tokens: [],
    isClient: false,
    domain: "layout",
    source: "level-peer-strip",
  },
  {
    name: "LevelSection",
    description: "Per-level section with left accent bar and atmospheric glow",
    pattern: null,
    tokens: [],
    isClient: false,
    domain: "layout",
    source: "level-section",
  },
  {
    name: "PromptCopyButton",
    description: "Copy-to-clipboard button with variant-driven styling",
    pattern: null,
    variants: [
      "rr",
      "planning",
      "synthesize",
      "curate",
      "workforce",
      "pipeline",
      "morning",
      "plan-tasks",
      "integration-review",
    ],
    tokens: [],
    isClient: true,
    domain: "layout",
    source: "prompt-copy-button",
  },
  {
    name: "ResizeHandle",
    description: "Pointer-based column resize handler with golden accent",
    pattern: null,
    tokens: ["color-gold"],
    isClient: true,
    domain: "layout",
    source: "resize-handle",
  },
  {
    name: "ScopeBadge",
    description: "Scope badge with color mapping from SCOPE_COLORS",
    pattern: "badge",
    tokens: [],
    isClient: false,
    domain: "layout",
    source: "scope-badge",
  },
  {
    name: "ScopeFilterBar",
    description: "Filter pills by scope with count badges",
    pattern: null,
    tokens: [],
    isClient: false,
    domain: "layout",
    source: "scope-filter-bar",
  },
  {
    name: "SectionHeader",
    description: "Uppercase monospace label with large display heading",
    pattern: "section-header",
    tokens: ["color-gold"],
    isClient: false,
    domain: "layout",
    source: "section-header",
  },
  {
    name: "SortControl",
    description: "Icon-based sort option buttons with active highlight",
    pattern: null,
    variants: ["activity", "updated", "alpha", "status"],
    tokens: [],
    isClient: true,
    domain: "layout",
    source: "sort-control",
  },
  {
    name: "StatusBadge",
    description: "Status pill with LED mode and semantic color mapping",
    pattern: "badge",
    variants: [
      "pending",
      "approved",
      "in-progress",
      "integrated",
      "declined",
      "archived",
      "active",
      "paused",
      "completed",
    ],
    tokens: [],
    isClient: false,
    domain: "layout",
    source: "status-badge",
  },
  {
    name: "StudioBreadcrumb",
    description: "Navigation breadcrumb with segment mapping and separators",
    pattern: null,
    tokens: [],
    isClient: false,
    domain: "layout",
    source: "studio-breadcrumb",
  },
  {
    name: "StudioHeader",
    description: "Mission Control title with monospace label and gradient border",
    pattern: "section-header",
    tokens: [],
    isClient: false,
    domain: "layout",
    source: "studio-header",
  },
  {
    name: "TreeNode",
    description: "Hierarchical expandable tree node with status badges",
    pattern: null,
    tokens: [],
    composedWith: ["StatusBadge", "PromptCopyButton"],
    isClient: true,
    domain: "layout",
    source: "tree-node",
  },

  // ── Content ────────────────────────────────────────────────────
  {
    name: "ActivityDescription",
    description: "Activity entry text with inline issue link parsing",
    pattern: null,
    tokens: [],
    isClient: false,
    domain: "content",
    source: "activity-description",
  },
  {
    name: "ActivityEntry",
    description: "Timeline entry with classification icon and vertical spine",
    pattern: "timeline",
    variants: ["milestone", "launch", "iteration", "update"],
    tokens: ["color-gold"],
    composedWith: ["ActivityDescription"],
    isClient: true,
    domain: "content",
    source: "activity-entry",
  },
  {
    name: "ActivityFullTimeline",
    description: "Multi-date grouped timeline with golden spine and scope badges",
    pattern: "timeline",
    tokens: ["color-gold"],
    composedWith: ["ScopeBadge"],
    isClient: false,
    domain: "content",
    source: "activity-full-timeline",
  },
  {
    name: "ActivityTimeline",
    description: "Wrapper mapping ActivityEntry array with parsed descriptions",
    pattern: "timeline",
    tokens: [],
    composedWith: ["ActivityEntry"],
    isClient: false,
    domain: "content",
    source: "activity-timeline",
  },
  {
    name: "DeliverableGrid",
    description: "3-column grid of deliverable cards with embedded charts",
    pattern: null,
    tokens: [],
    composedWith: ["ChartRenderer"],
    isClient: true,
    domain: "content",
    source: "deliverable-grid",
  },
  {
    name: "DocRenderer",
    description: "React-markdown with custom heading, link, code, and table overrides",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "content",
    source: "doc-renderer",
  },
  {
    name: "DocSearch",
    description: "Fuse.js fuzzy search with autocomplete dropdown",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "content",
    source: "doc-search",
  },
  {
    name: "ExportSurface",
    description: "Dual-layout export/type listing with desktop and mobile modes",
    pattern: null,
    tokens: [],
    composedWith: ["TypeDetailPanel"],
    isClient: true,
    domain: "content",
    source: "export-surface",
  },
  {
    name: "MermaidDiagram",
    description: "Lazy-loaded mermaid renderer with D3-style theme variables",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "content",
    source: "mermaid-diagram",
  },
  {
    name: "NextResearchPrompt",
    description: "Research prompt display with copy button and seed questions",
    pattern: null,
    tokens: [],
    composedWith: ["PromptCopyButton"],
    isClient: true,
    domain: "content",
    source: "next-research-prompt",
  },
  {
    name: "ResearchLibrary",
    description: "Collapsible research file structure with iteration groups",
    pattern: null,
    tokens: ["color-copper", "color-gold"],
    isClient: true,
    domain: "content",
    source: "research-library",
  },
  {
    name: "ResearchTree",
    description: "Server component wrapper rendering research tree with data",
    pattern: null,
    tokens: [],
    composedWith: ["ResearchTreeClient"],
    isClient: false,
    domain: "content",
    source: "research-tree",
  },
  {
    name: "ResearchTreeClient",
    description: "Client tree rendering with open questions collapsible section",
    pattern: null,
    tokens: [],
    composedWith: ["TreeNode"],
    isClient: true,
    domain: "content",
    source: "research-tree-client",
  },
  {
    name: "SlideDeck",
    description: "Presentation viewer with keyboard controls and slide transitions",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "content",
    source: "slide-deck",
  },

  // ── Data Visualization ─────────────────────────────────────────
  {
    name: "AbstractionLadder",
    description: "Horizontal level nodes with dependency ticks and ring highlight",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "data-viz",
    source: "abstraction-ladder",
  },
  {
    name: "AbstractionSpine",
    description: "Horizontal spine with nodes/arrows, mobile pill strip",
    pattern: null,
    tokens: [],
    isClient: false,
    domain: "data-viz",
    source: "abstraction-spine",
  },
  {
    name: "ActivityStatsBar",
    description: "Statistics bar showing entry count, date range, and top scope",
    pattern: "data-readout",
    tokens: [],
    isClient: false,
    domain: "data-viz",
    source: "activity-stats-bar",
  },
  {
    name: "ApiCompositionGraph",
    description: "Layered visualization of primitives by abstraction level",
    pattern: null,
    tokens: [],
    isClient: false,
    domain: "data-viz",
    source: "api-composition-graph",
  },
  {
    name: "ChartRenderer",
    description: "Generic Recharts wrapper for bar/line/area/pie/radar charts",
    pattern: null,
    variants: ["bar", "line", "area", "pie", "radar"],
    tokens: [],
    isClient: true,
    domain: "data-viz",
    source: "chart-renderer",
  },
  {
    name: "DependencyGraph",
    description: "Upstream/downstream primitive dependency sections",
    pattern: null,
    tokens: [],
    isClient: false,
    domain: "data-viz",
    source: "dependency-graph",
  },
  {
    name: "DocsCategoryChart",
    description: "Recharts bar chart of document count by category",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "data-viz",
    source: "docs-category-chart",
  },
  {
    name: "EclipseActivationChart",
    description: "D3 interactive chart with focus+context brush zooming",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "data-viz",
    source: "eclipse-activation-chart",
  },
  {
    name: "EclipseActivationTable",
    description: "Sortable activation event table with highlight-on-hit rows",
    pattern: "data-readout",
    tokens: [],
    isClient: true,
    domain: "data-viz",
    source: "eclipse-activation-table",
  },
  {
    name: "PortfolioHealthChart",
    description: "Horizontal stacked bar of onTrack/blocked/paused tasks",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "data-viz",
    source: "portfolio-health-chart",
  },
  {
    name: "ProcessGraph",
    description: "D3 force-directed graph of process node relationships",
    pattern: null,
    tokens: [
      "color-gold",
      "color-copper",
      "color-bronze",
    ],
    isClient: true,
    domain: "data-viz",
    source: "process-graph",
  },
  {
    name: "ProcessPipelineChart",
    description: "Horizontal stacked bar for 4 process statuses",
    pattern: "pipeline-bar",
    tokens: ["color-copper"],
    isClient: false,
    domain: "data-viz",
    source: "process-pipeline-chart",
  },
  {
    name: "ResearchDataTable",
    description: "Sortable table of Saturn quarter-cycle events",
    pattern: "data-readout",
    tokens: [],
    isClient: true,
    domain: "data-viz",
    source: "research-data-table",
  },
  {
    name: "SaturnLongitudeChart",
    description: "Recharts composed chart with area showing longitude over time",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "data-viz",
    source: "saturn-longitude-chart",
  },
  {
    name: "SignificanceChart",
    description: "Bar chart showing significance score distribution with gradient",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "data-viz",
    source: "significance-chart",
  },

  // ── Agents ─────────────────────────────────────────────────────
  {
    name: "RoleEditor",
    description: "Form editor for agent role with category and pattern selects",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "agents",
    source: "role-editor",
  },
  {
    name: "TaskDetailContent",
    description: "Task detail page with breadcrumb, badges, objective, criteria",
    pattern: null,
    tokens: [],
    composedWith: ["StatusBadge", "StudioBreadcrumb"],
    isClient: true,
    domain: "agents",
    source: "task-detail-content",
  },
  {
    name: "TaskSummaryWidget",
    description: "Compact task pipeline with status count pills",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "agents",
    source: "task-summary-widget",
  },
  {
    name: "TasksContent",
    description: "Task board with pipeline cards, filter bar, and sortable table",
    pattern: null,
    tokens: [],
    composedWith: ["StatusBadge"],
    isClient: true,
    domain: "agents",
    source: "tasks-content",
  },
  {
    name: "WorkforceContent",
    description: "Workforce dashboard with summary stats and role cards",
    pattern: null,
    tokens: [],
    composedWith: ["TaskSummaryWidget"],
    isClient: true,
    domain: "agents",
    source: "workforce-content",
  },

  // ── Domain Panels ──────────────────────────────────────────────
  {
    name: "ApiCurlExample",
    description: "cURL command display with copy button and auth handling",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "domain-panels",
    source: "api-curl-example",
  },
  {
    name: "ApiEndpointCard",
    description: "Endpoint card with method badge, path, level, and auth indicator",
    pattern: null,
    tokens: [],
    composedWith: ["ApiMethodBadge", "LevelBadge"],
    isClient: false,
    domain: "domain-panels",
    source: "api-endpoint-card",
  },
  {
    name: "EventBrowserPanel",
    description: "Paginated transit event browser with status/duration filters",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "domain-panels",
    source: "event-browser-panel",
  },
  {
    name: "McpContent",
    description: "MCP dashboard with server config, LM Studio, event log, tools",
    pattern: null,
    tokens: ["color-mcp"],
    isClient: true,
    domain: "domain-panels",
    source: "mcp-content",
  },
  {
    name: "PrimitiveApiSurface",
    description: "Compact endpoint cards for primitives exposed via API",
    pattern: null,
    tokens: [],
    composedWith: ["ApiMethodBadge", "LevelBadge"],
    isClient: false,
    domain: "domain-panels",
    source: "primitive-api-surface",
  },
  {
    name: "PrimitiveCard",
    description: "Two variants: curated with metadata/gauge or uncategorized minimal",
    pattern: "card-list",
    tokens: ["color-gold"],
    composedWith: ["LevelBadge", "KindBadge"],
    isClient: false,
    domain: "domain-panels",
    source: "primitive-card",
  },
  {
    name: "PrimitivesStagger",
    description: "Motion container with stagger animation for catalog sections",
    pattern: null,
    tokens: [],
    isClient: true,
    domain: "domain-panels",
    source: "primitives-stagger",
  },
  {
    name: "TypeDetailPanel",
    description: "Sticky panel showing TypeScript signature with kind renderers",
    pattern: null,
    tokens: [],
    composedWith: ["KindBadge"],
    isClient: true,
    domain: "domain-panels",
    source: "type-detail-panel",
  },
]

// ── Lookup helpers ─────────────────────────────────────────────────

/** Find a component by PascalCase name */
export function getComponent(
  name: string
): ComponentCatalogEntry | undefined {
  return COMPONENT_CATALOG.find((c) => c.name === name)
}

/** List all components implementing a given pattern */
export function getComponentsByPattern(
  pattern: ComponentCatalogEntry["pattern"]
): ComponentCatalogEntry[] {
  return COMPONENT_CATALOG.filter((c) => c.pattern === pattern)
}

/** List all components in a given domain */
export function getComponentsByDomain(
  domain: ComponentCatalogEntry["domain"]
): ComponentCatalogEntry[] {
  return COMPONENT_CATALOG.filter((c) => c.domain === domain)
}

/** List all components that compose with a given component */
export function getComponentsByComposition(
  name: string
): ComponentCatalogEntry[] {
  return COMPONENT_CATALOG.filter((c) => c.composedWith?.includes(name))
}
