export { openDb, closeAll, resolveDbPaths } from "./connection"
export { applyCoordinationSchema, COORDINATION_SCHEMA_VERSION } from "./coordination-schema"
export { applyEventsSchema, appendEvent } from "./events-schema"
export { applyKnowledgeSchema, KNOWLEDGE_SCHEMA_VERSION } from "./knowledge-schema"
export { syncFromFilesystem, syncAllProjects } from "./knowledge-sync"
export { syncEmbeddings } from "./knowledge-embeddings"
export { classifyFile, extractEdgesFromFrontmatter, computeContentHash } from "./classify"
export type { ResolvedDbPaths } from "./types"
export type { EventInput } from "./events-schema"
export type { SyncStats } from "./knowledge-sync"
export type { EmbeddingSyncStats } from "./knowledge-embeddings"
export type { FileClassification, Edge } from "./classify"
